# Generated by Django 5.1.2 on 2026-01-18 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('EmailSettingID', models.AutoField(primary_key=True, serialize=False)),
                ('SmtpServer', models.CharField(max_length=255)),
                ('SmtpPort', models.IntegerField()),
                ('Username', models.CharField(max_length=255)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('IsEnabled', models.BooleanField(default=False)),
                ('LastChecked', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Email Settings',
                'db_table': 'EmailSettings',
            },
        ),
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('IntegrationID', models.AutoField(primary_key=True, serialize=False)),
                ('IntegrationName', models.CharField(max_length=255)),
                ('ApiKey', models.CharField(max_length=255)),
                ('IsEnabled', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Integrations',
                'db_table': 'Integrations',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('PermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('PermissionName', models.CharField(max_length=255, unique=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Permissions',
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('ProgramID', models.AutoField(primary_key=True, serialize=False)),
                ('ProgramName', models.CharField(max_length=255)),
                ('ProgramDescription', models.TextField()),
                ('ProgramImage', models.URLField(blank=True, max_length=500, null=True)),
                ('Duration', models.CharField(help_text='e.g., 3 Months, 6 Weeks', max_length=100)),
                ('Language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic'), ('Bilingual', 'Bilingual')], default='English', max_length=50)),
                ('Location', models.CharField(choices=[('On-site (Riyadh)', 'On-site (Riyadh)'), ('On-site (Jeddah)', 'On-site (Jeddah)'), ('On-site (Dammam)', 'On-site (Dammam)'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], default='On-site (Riyadh)', max_length=100)),
                ('TargetAudience', models.CharField(help_text='e.g., Fresh Graduates, Professionals', max_length=100)),
                ('Status', models.CharField(choices=[('open', 'Open'), ('upcoming', 'Upcoming'), ('closed', 'Closed')], default='open', max_length=20)),
                ('Requirements', models.TextField(blank=True, help_text='Program requirements', null=True)),
                ('Benefits', models.TextField(blank=True, help_text='Program benefits', null=True)),
                ('Curriculum', models.TextField(blank=True, help_text='Program curriculum', null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('ApplicationDeadline', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Programs',
                'db_table': 'Programs_Table',
                'ordering': ['-CreatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=255, unique=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='StatusDictionary',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusCode', models.CharField(max_length=50, unique=True)),
                ('StatusName', models.CharField(max_length=255)),
                ('StageClassification', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Status Dictionary',
                'db_table': 'StatusDictionary',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255, unique=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(max_length=255)),
                ('workflow_name', models.CharField(max_length=255)),
                ('current_step_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='started', max_length=255)),
                ('initiated_by_email', models.EmailField(max_length=254)),
                ('initiated_by_clerk_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('RolePermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('PermissionID', models.ForeignKey(db_column='PermissionID', on_delete=django.db.models.deletion.PROTECT, to='app.permissions')),
                ('RoleID', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.PROTECT, to='app.roles')),
            ],
            options={
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'RolePermissions',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('UserRoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleID', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.PROTECT, to='app.roles')),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, to='app.users')),
            ],
            options={
                'verbose_name_plural': 'User Roles',
                'db_table': 'UserRoles',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('AuditLogID', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Metadata', models.JSONField(blank=True, null=True)),
                ('UserID', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users')),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'AuditLog',
            },
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('execution_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_id', models.CharField(max_length=255)),
                ('step_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=255)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('executed_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('step_data', models.JSONField(default=dict, help_text='JSON data containing the step form submission')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='app.workflowinstance')),
            ],
            options={
                'unique_together': {('workflow_instance', 'step_id')},
            },
        ),
    ]
