# Generated by Django 5.1.2 on 2026-01-19 13:23

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Story title', max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Full story content', verbose_name='Description')),
                ('author_name', models.CharField(help_text='Graduate name', max_length=100)),
                ('author_image', models.URLField(blank=True, help_text="URL to author's photo", max_length=500, null=True)),
                ('story_image', models.URLField(help_text='URL to story featured image', max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, help_text='Rating out of 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('category', models.CharField(choices=[('program', 'Programs'), ('career', 'Career Growth'), ('achievement', 'Achievements'), ('leadership', 'Leadership'), ('other', 'Other')], default='other', help_text='Story category', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured story (shown prominently)')),
                ('is_published', models.BooleanField(default=True, help_text='Publish status')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Success Story',
                'verbose_name_plural': 'Success Stories',
                'db_table': 'success_stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
