# Generated by Django 5.1.2 on 2026-01-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('MediaID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Image', models.URLField(max_length=500)),
                ('Type', models.CharField(choices=[('news', 'News'), ('events', 'Events'), ('gallery', 'Gallery'), ('others', 'Others')], default='news', max_length=20)),
                ('EventStatus', models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], help_text='Status for event type only', max_length=20, null=True)),
                ('EventDate', models.DateTimeField(blank=True, help_text='Event date (for upcoming events countdown)', null=True)),
                ('MediaType', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], help_text='Media type for gallery items', max_length=20, null=True)),
                ('Facility', models.CharField(blank=True, help_text='Facility name for gallery items', max_length=255, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Media',
                'db_table': 'Media',
                'ordering': ['-CreatedAt'],
            },
        ),
    ]
