# Generated by Django 5.1.2 on 2026-01-21 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='EndDate',
            field=models.DateField(blank=True, help_text='Event end date', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='EndTime',
            field=models.TimeField(blank=True, help_text='Event end time', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='EventFlyer',
            field=models.URLField(blank=True, help_text='Event flyer PDF URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='EventFlyerFileName',
            field=models.CharField(blank=True, help_text='Event flyer file name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='Fee',
            field=models.CharField(blank=True, help_text='Event fee', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='Languages',
            field=models.CharField(blank=True, help_text="Event languages (e.g., 'Arabic, English')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='Location',
            field=models.CharField(blank=True, help_text='Event location name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='LocationAddress',
            field=models.TextField(blank=True, help_text='Full event location address', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='LongDescription',
            field=models.TextField(blank=True, help_text='Detailed description for event details page', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='Speaker',
            field=models.CharField(blank=True, help_text='Event speaker name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='SpeakerImage',
            field=models.URLField(blank=True, help_text='Event speaker image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='StartDate',
            field=models.DateField(blank=True, help_text='Event start date', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='StartTime',
            field=models.TimeField(blank=True, help_text='Event start time', null=True),
        ),
    ]
