# Generated by Django 5.1.2 on 2026-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_interest', models.CharField(choices=[('complaint', 'Complaint'), ('cooperation', 'Cooperation'), ('inquiry', 'General Inquiry')], default='complaint', help_text='Type of contact inquiry', max_length=50)),
                ('name', models.CharField(help_text='Contact person name', max_length=255)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Optional phone number', max_length=50, null=True)),
                ('message', models.TextField(help_text='Contact message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
