# Generated by Django 5.1.2 on 2026-01-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_media_enddate_media_endtime_media_eventflyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Slug', models.SlugField(max_length=255, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Icon', models.CharField(blank=True, help_text='Icon name or class', max_length=100, null=True)),
                ('Order', models.IntegerField(default=0, help_text='Display order')),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'db_table': 'FAQCategories',
                'ordering': ['Order', 'Name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('FAQID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=500)),
                ('Answer', models.TextField()),
                ('Order', models.IntegerField(default=0, help_text='Display order within category')),
                ('IsActive', models.BooleanField(default=True)),
                ('HelpfulCount', models.IntegerField(default=0)),
                ('NotHelpfulCount', models.IntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.faqcategory')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'db_table': 'FAQs',
                'ordering': ['Order', 'Question'],
            },
        ),
    ]
