# Generated by Django 5.1.2 on 2026-01-19 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('ReportName', models.CharField(max_length=100)),
                ('SqlQuery', models.TextField()),
                ('ReportType', models.CharField(choices=[('pie chart', 'Pie Chart'), ('bar chart', 'Bar Chart'), ('line chart', 'Line Chart'), ('doughnut chart', 'Doughnut Chart'), ('table chart', 'Table Report')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'db_table': 'Reports_Table',
            },
        ),
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reports')),
            ],
            options={
                'verbose_name_plural': 'Report Groups',
                'db_table': 'Report_Groups_Table',
                'unique_together': {('report', 'group')},
            },
        ),
    ]
